def/def.go

As in hroot, we may as well provide an array for a command and its arguments.

Discussion: Strongly-type entrypoint arguments

---

lib/treewalk/walk.go
lib/treewalk/walk_test.go

A simple iterator interface that, when implemented, lets you conveniently do a visitor pattern walk on a tree.  Critically, with both pre-order and post-order visitation... which means after this is merged, I can replace `filepath.Walk` and fix the remaining skipped tests in the `dir` input implementation that need post-order visitation to build.  Right after that, also will be useful for walking trees in the hash buckets and building the final hash.
Consumer code tends to end up with a type assertion as the first step in every `WalkFunc`.  I can't think of any way to make this suck less... of course Generics would, but... golang.
(More general than repeatr?  Absolutely.  Resisting the temptation to put it in a grabbag "golang-utils" library until we actually discover an impetus to do …

Treewalker

---

README.md
cli/cli_test.go
goad
lib/integration/basic.json

* Fix CLI tests to run from the 'correct' directory, to get rid of dumb `../` prefixes
* Because of this, the basic integration test can double as a human-friendly demo
* Added some demonstration instructions!

Better cli test

---

executor/chroot/chroot_executor.go
executor/dispatch/dispatch.go
executor/executor.go
executor/nsinit/nsinit.go
executor/null/nil_executor.go
input/input.go
lib/flak/assist.go

* Adds a `Configure(workspacePath string)` method to executor interface
* Added some quick documentation to a few files explaining expectations
* Unify executor's usage of temp job directory logic

Unify jobdirs

---

executor/chroot/chroot_executor.go
executor/chroot/chroot_executor_test.go

Goconvey's default behavior is to abort as soon as one assertion fails.  Adding the `FailureContinues` parameter to a block means any failure still fails the overall block, but will continue to do other checks in the block.  Here, this is useful to see differences in stdout/err even if, e.g., the exit code was nonzero (which is in fact when those strings are the most useful!).

Check all outputs from test executions

---

README.md
executor/nsinit/nsinit.go
goad
lib/integration/basic.json

Turns out.... I had an `nsinit` binary on my system PATH the whole time. Functional reproducible environments, we have them.
This sets up `./goad exec` to run repeatr with a modified PATH until we fix nsinit binaries being a prerequisite. It also actually... checks the error when trying to run nsinit, so we know if it fails. Derp.

Fix nsinit pathing to actually work

---

def/somewhen.go
input/dir/dir_input_test.go
lib/fshash/fs_walk.go
lib/fspatch/utimes_darwin.go
lib/fspatch/utimes_freebsd.go
lib/fspatch/utimes_linux.go
lib/fspatch/utimes_test.go
lib/fspatch/utimes_unsupported.go

These are just a bunch of targets-of-opportunity snipes of things that were getting on my nerves working with more upcoming test fixtures stuff.  Also, if the kernel tells us a sycall isn't supported, that's consistently an error now.

fspatch updates

---

executor/chroot/chroot_executor.go

Yank in https://github.com/polydawn/errors latest.  Use a feature of that to make one of the recently added cleanup chains do its work without mutating the error it's responding to but not per-se handling.

Errors upgrade

---

.gitmodules
lib/flak/provision.go
output/dir/dir_output.go
output/dir/dir_output_test.go
output/errors.go
output/output.go
output/tar/tar_output.go
output/tar2/tar_output.go
output/tar2/tar_output_test.go
output/tests/output_tests.go

Add a hashing tar output implementation.
This hashing tar output implementation is happily tiny: treewalk and fshash.bucket stuff was totally reusable, as intended... so basically all that needed to happen here was wiring the file body io streams.
Interfaces extended to support the new data returns.
Includes a new test package which uses the file fixtures, and itself refers only to the output interface -- zero references to the tar (or any other) implementation.  So these can be reused by every output implementation in the future!  All hail the table-driven specs.

Tar output

---

cli/cli.go
cli/run.go
executor/basicjob/basic.go
executor/chroot/chroot_executor.go
executor/chroot/chroot_executor_test.go
executor/dispatch/dispatch.go
executor/executor.go
executor/nsinit/nsinit.go
executor/null/null_executor.go
scheduler/dispatch/dispatch.go
scheduler/errors.go
scheduler/group/group.go
scheduler/linear/linear.go
scheduler/scheduler.go

Branch name is a slight misnomer, as two schedulers landed.
* Added some docs to Executor interface methods.
* Designed a nascent Scheduler interface
* Landed a linear scheduler. Runs one job at a time.
* Landed a group scheduler. Runs N jobs at a time, defaulting to the number of virtual CPU.
The linear scheduler was originally intended as a most-basic example of how to write a scheduler. Previous comments to the effect of "why not just use group with N=1" are not wrong; I would like to keep linear around regardless to ensure we always have a dead-simple reference. And, well, >1 implementations of an interface is better than one. Open to disagreement.
At minimum, left to do:
* Executor interface proposal was agreed on, take action
I wanted to get this into PR status so we can catch …

Schedulers!

---

input/errors.go
input/input.go
input/tar/tar_input.go
output/tar/tar_output.go

Start upgrading use of exec to use [Gosh](https://github.com/polydawn/gosh/).
Using gosh means their error handling is now consistent in all the ways gosh addresses (exit codes are accounted for, signals are accounted for, ptrace is accounted for, etc; we can remove that copyforked stuff from repeatr).   In the cases upgraded here, we also now make operations silently (not mucking up the host terminal), and if something goes wrong then (and only then) attach output to the error we're about to raise -- this fixes a few places where goconvey was reporting fails because of misdirected output.

Exec upgrades

---

lib/streamer/cbor_streamer.go
lib/streamer/cbor_streamer_test.go
lib/streamer/streamer.go

Add a stream logging and mux/demuxing system.
After creating a mux, one can get labeled writers to it, and readers that return the conjunction of any choice of labels.  Every reader starts off again from the beginning.  This implementation is backed by files, so it's safe for arbitrarily large amounts of data.  Readers can safely run concurrently with writers; the readers will return as much as they can, and when out of data will continue to block until the writers emit close signals (even if the reader catches up with the current end of file while any relevant writer is still ongoing).
The intended/example use case for this is collecting stdout and stderr from a process, saving both of them, and being able reply either alone or both together, always in the same order they originally …

Stream muxer

---

cli/run.go
executor/chroot/chroot_executor.go
executor/chroot/chroot_executor_test.go
executor/nsinit/nsinit.go
lib/flak/provision.go
lib/integration/basic.json

* Hooks up the new stream mux to executors.
* Delays handing off the Job until the muxes are ready.
* Does nothing to improve the Job situation; that's a different topic
* Now that we have nicer error handling, squelch redundant reporting
* Stream job output from mux to CLI in real time

Use mux in executors

---

cli/cli.go
cli/cli_test.go
cli/errors.go
cli/run.go
executor/chroot/chroot_executor.go
executor/chroot/chroot_executor_test.go
executor/executor.go
executor/nsinit/nsinit.go
executor/null/null_executor.go
executor/util/provision.go
repeatr.go
scheduler/group/group.go
scheduler/linear/linear.go

All output from the CLI can now be shunted to any `io.Writer`.  Tests can use this to check output.  Right now, existing tests route everything to `ioutil.Discard` for lack of any useful assertions.
This cleans up *all* output leaking through test reports, making reading much more pleasant again.
Introduced new errors for user-facing messages, with graceful reporting for and a mechanism for custom exit codes, as well as a polite logging mechanism for unexpected errors.

Universal output redirection, more exit handling

---

executor/chroot/chroot_executor.go
executor/chroot/chroot_executor_test.go
executor/nsinit/nsinit.go
lib/flak/assist.go

Cleanups and fail-safe behavior for some executor failure modes.
- Always close stream muxes
- Set default values for more return codes.  (Zero values were overlaping with valid values (namely, with exit codes), so initializing an unambiguous value is a big deal for maintaining appearances of sanity in error handling paths.  As a specific example, it makes sense for assertions that the exit code is zero-aka-success should fail if the process never launched.)
- Add some more error condition checks in tests that always should've been there.

Executor failsafe results

---

cli/cli_test.go
executor/chroot/chroot_executor_test.go
input/dir/dir_input_test.go
input/tar2/tar_input_test.go
input/tests/input_tests.go
output/tar2/tar_output_test.go
output/tests/output_tests.go
testutil/filefixture/file_fixtures_test.go
testutil/requirements.go

Tests with a bunch of prereqs were getting clunky to express.  Replaced the prior pattern with https://github.com/smartystreets/goconvey/wiki/Decorating-tests-to-provide-common-logic instead.
Also now generates a short report node to tell you *why* a test group was skipped.

Test requirements system

---

lib/fs/emplacements.go

Add a consistent MkdirAll to lib/fs.  Like os.MkdirAll, but flattens out attributes.
This is a feature wanted by the upcoming assembler systems.

Add a consistent MkdirAll to lib/fs.

---

testutil/filefixture/types.go

Test fixtures should be free to create their parent dirs.

Test fixtures should be free to create their parent dirs

---

input/tar2/tar_input.go
lib/flak/hash.go
lib/fshash/fs_walk.go

Export HashingReader.  It lets us use e.g. `PlaceFile()` without extra copy workers.
Quietly fixes a bug in dir inputs: permissions bits on files were not being correctly set, and now are by virtue of reusing the already-tested paths in fs.PlaceFile.  (Tests coming as part of the io-reboot refactor will cover this.)
Yayy for diffs that are net removals of code!

Export HashingReader.  Fix dir input to use.

---

input/dir/dir_input.go
input/errors.go
input/s3/s3_input.go
input/tar2/tar_input.go

Sticking values irretreivably in fmt strings is a poor idea.  Put them into data keys instead, so they can be re-examined later.
Also, standardize the way HashMismatchError are created, so their fmt strings aren't copypasta'd around.

Attach hashes structurally to HashMismatchErrors.

---

cli/cli.go
cli/cli_test.go
cli/run.go
cli/run_command.go
cli/scan_command.go
demo.sh
executor/util/provision.go
input/s3/s3_input.go
repeatr.go
scheduler/group/group.go
scheduler/linear/linear.go
scheduler/scheduler.go

CLI upgrades, and a new `repeatr scan` subcommand.
`repeatr scan` invokes the output scan & upload functionality on a local filesystem path.  It produces a json chunk on stdout that can be used directly as configuration for an input.
Some logging that was getting devnull'd has been reconnected (though shoddily -- we need a logging framework, stat).
Fix output of CLIErrors to be more friendly.
A `demo.sh` script now exists.  This does a slow, semi-interactive showcase of a variety of repeatr features, invoked from bash exactly as a normal user would.
:warning: contains (lots of) commits from other PRs: rebasing will remove them after #52 lands.  EDIT: done.

Scan command

---

executor/chroot/chroot_executor.go
executor/chroot/chroot_executor_test.go
executor/dispatch/dispatch.go
executor/errors.go
executor/nsinit/nsinit_executor_test.go
executor/runc/runc_config.go
executor/runc/runc_config_test.go
executor/runc/runc_executor.go
executor/runc/runc_executor_test.go
executor/tests/env_tests.go
executor/tests/exec_tests.go
executor/tests/fs_tests.go
io/assets/assets.go
io/assets/errors.go
lib/streamer/cbor_streamer.go
lib/streamer/tail.go
testutil/logging.go
testutil/misc.go

Add a new executor plugin, this time backed by containers powered by runc!
Also, there's an asset management and bootstrapping tool wedged in there, which is used to obtain a well known version of a runc executable (e.g. exact same as we used when testing) in a safe integrity-guaranteed way.

Runc executor

---

.travis.yml
goad
io/placer/assembler_test.go
io/transmat/git/git_transmat.go
io/transmat/git/git_warehouse.go

Travis should test non-root runs of the tests (most of them will skip themselves, but *that* should also be tested to work properly).
Also, we should not run repeat-thyself as an integration test in *some* travis builds, because their pattern of testing merge commits makes a synthetic commit that isn't readily fetchable.

Make travis more useful

---

.gitmodules
io/transmat/gs/doc.go
io/transmat/gs/errors.go
io/transmat/gs/gs_stream.go
io/transmat/gs/gs_token.go
io/transmat/gs/gs_transmat.go
io/transmat/gs/gs_transmat_test.go

This should enable the use of Google cloud storage.

Google cloud storage

---

core/cli/twerk_command.go

Adds the option to run `twerk` with different policies.
e.g. `repeatr twerk -P governor`

Allow policy changes in introspective mode.

---

.gitmodules
CHANGELOG.md
core/executor/util/capabilities.go
lib/fs/emplacements.go
rio/transmat/impl/git/git_cmd.go
rio/transmat/impl/git/git_internals.go
rio/transmat/impl/git/git_transmat.go
rio/transmat/impl/git/git_uri_parsing.go
rio/transmat/impl/git/git_utils.go
rio/transmat/impl/git/git_workarea.go

Massive overhaul to the git transmat, which should increase efficiency and successful caching.
- Submodules are now cached: if you have a parent project move to a new commit, but keep all the same submodule versions, previously repeatr was oblivious; now, it's a fast 100% cache hit.
- Git data objects are now cached: fetches are incremental when using the same remote repos.
- Slight change: ".git" files in submodule paths no longer leak into the container's sight.  This shouldn't affect you unless you had output configurations exporting filesystems including such files.

Git overhaul -- fetch/checkout/submodule splits

---

rio/transmat/impl/git/git_transmat.go

Move root repo checkout before some other more complex operations, so that errors about hash not present in repo come out more clearly again.
(Follow-on to the previous batch of big changes here.)

git-clearer-dne

---

CHANGELOG.md
lib/fs/emplacements.go
rio/placer/assembler.go
rio/placer/impl/aufs/aufsPlacer.go
rio/placer/impl/bind/bindPlacer.go
rio/placer/impl/copy/copyingPlacer.go
rio/placer/tests/placer_tests.go

Support for (and test coverage for) using plain files in `rio/placer.Assembler`.
... meaning: the "file" transmat can be used in full formulas, as can bind mounts of individual files from the host.

Assembler file support

---

api/def/base58.go
api/def/formula.go
api/def/formula_hash_test.go

(Finally!...) Add a `Hash()` function to `def.Formula`.
As the docs on the function describe: this function will return a string that may be expected to converge for formulae which describe identical setups.  Some elements of the structure that are *not* relevant to correctly reproducing the contained task (namely, data storage urls) are explicitly not included under the hash.
This has been a long time in coming: enabling this hash, and its semantics, have been a guiding factor in every part of Repeatr's design.  This hash [*] is effectively a content-addressable description of a computation to be performed, complete with environment.  This can be a primary key in a globally distributable database of *things that can be computed*; a single string usable as an index over arbitrary …

Formula hash func

---

core/executor/cradle/cradle.go

Add normalization of the CWD perms to cradle's responsibilities.
The cradle package already does a bunch of work to make sure the container filesystem is a reasonable place to launch the user's process in.  It's desirable to keep this interference to a minimum, because every thing we add here implicitly becomes part of repeatr's contract and is a potential leakage through the otherwise absolute specificity of formulas.  In this case the reasons are still compelling: the path affected *is* specified by the formula; we are already interfering with that path; and this change set just refines the interference a bit.  (We should still probably have a flag to disable this interference entirely; not having that is a somewhat shameful omission, but adding it is a separate task.)
Previously, the …

Normalize work dir perms

---

rio/transmat/impl/git/git_transmat.go

Remove admonishment in git transmat docs; it has in fact improved well beyond that point!
Snipefix, noticed during reviewing https://github.com/polydawn/repeatr/pull/107 .

Git docs fix

---

rio/errors.go

The absence of this in the whitelist for valid errors for rio packages to return was an oversight.  The tar transmat already returns these in several places, and it is indeed a semantic and correct error to return.
Snipefix, noticed while reviewing https://github.com/polydawn/repeatr/pull/107 .

rio: add ErrWareCorrupt to the returnable set.
